"""SQLite persistence foundation for Chief Site Engineer."""

from .contracts import (
    ATTACHMENT_STATUSES,
    INITIAL_REVISION,
    OBSERVATION_STATUSES,
    serialize_utc_timestamp,
    validate_observation_state,
    validate_record_id,
    validate_utc_timestamp,
)
from .migrations import connect_database, migrate_database
from .errors import (
    ArchivedRecordError,
    ConstraintViolation,
    DuplicateRecordError,
    ForeignKeyViolation,
    InvalidRecordError,
    InvalidTransition,
    PersistenceError,
    RecordNotFound,
    RevisionConflict,
    UnitOfWorkStateError,
)
from .records import (
    OBSERVATION_EVENT_TYPES,
    AttachmentMetadataRecord,
    ObservationEventRecord,
    ProjectRecord,
    serialize_event_payload,
)
from .field_tracking_repositories import (
    FollowUpEventRepositoryPort,
    FollowUpRepositoryPort,
    RoutineOccurrenceEventRepositoryPort,
    RoutineOccurrenceRepositoryPort,
    RoutineTemplateEventRepositoryPort,
    RoutineTemplateRepositoryPort,
    SQLiteFollowUpEventRepository,
    SQLiteFollowUpRepository,
    SQLiteRoutineOccurrenceEventRepository,
    SQLiteRoutineOccurrenceRepository,
    SQLiteRoutineTemplateEventRepository,
    SQLiteRoutineTemplateRepository,
)
from .field_tracking_mapping import (
    follow_up_event_from_row,
    follow_up_event_to_row,
    follow_up_from_row,
    follow_up_to_row,
    routine_occurrence_event_from_row,
    routine_occurrence_event_to_row,
    routine_occurrence_from_row,
    routine_occurrence_to_row,
    routine_template_event_from_row,
    routine_template_event_to_row,
    routine_template_from_row,
    routine_template_to_row,
)
from .repositories import (
    AttachmentMetadataRepositoryPort,
    FieldObservationRepositoryPort,
    ObservationEventRepositoryPort,
    ProjectRepositoryPort,
    SQLiteFieldObservationRepository,
    SQLiteAttachmentMetadataRepository,
    SQLiteObservationEventRepository,
    SQLiteProjectRepository,
)
from .schema import SCHEMA_MIGRATIONS, SCHEMA_VERSION, Migration
from .unit_of_work import SQLiteUnitOfWork

__all__ = [
    "ATTACHMENT_STATUSES",
    "AttachmentMetadataRecord",
    "AttachmentMetadataRepositoryPort",
    "ArchivedRecordError",
    "ConstraintViolation",
    "DuplicateRecordError",
    "FieldObservationRepositoryPort",
    "FollowUpEventRepositoryPort",
    "FollowUpRepositoryPort",
    "ForeignKeyViolation",
    "INITIAL_REVISION",
    "InvalidRecordError",
    "InvalidTransition",
    "OBSERVATION_EVENT_TYPES",
    "OBSERVATION_STATUSES",
    "ObservationEventRecord",
    "ObservationEventRepositoryPort",
    "PersistenceError",
    "ProjectRecord",
    "ProjectRepositoryPort",
    "RecordNotFound",
    "RevisionConflict",
    "RoutineOccurrenceEventRepositoryPort",
    "RoutineOccurrenceRepositoryPort",
    "RoutineTemplateEventRepositoryPort",
    "RoutineTemplateRepositoryPort",
    "SCHEMA_MIGRATIONS",
    "SCHEMA_VERSION",
    "SQLiteFieldObservationRepository",
    "SQLiteFollowUpEventRepository",
    "SQLiteFollowUpRepository",
    "SQLiteAttachmentMetadataRepository",
    "SQLiteObservationEventRepository",
    "SQLiteProjectRepository",
    "SQLiteRoutineOccurrenceEventRepository",
    "SQLiteRoutineOccurrenceRepository",
    "SQLiteRoutineTemplateEventRepository",
    "SQLiteRoutineTemplateRepository",
    "SQLiteUnitOfWork",
    "UnitOfWorkStateError",
    "Migration",
    "connect_database",
    "follow_up_event_from_row",
    "follow_up_event_to_row",
    "follow_up_from_row",
    "follow_up_to_row",
    "migrate_database",
    "routine_occurrence_event_from_row",
    "routine_occurrence_event_to_row",
    "routine_occurrence_from_row",
    "routine_occurrence_to_row",
    "routine_template_event_from_row",
    "routine_template_event_to_row",
    "routine_template_from_row",
    "routine_template_to_row",
    "serialize_utc_timestamp",
    "serialize_event_payload",
    "validate_observation_state",
    "validate_record_id",
    "validate_utc_timestamp",
]
