OK = "OK"
MISSING_FILE = "MISSING_FILE"
ORPHAN_FILE = "ORPHAN_FILE"
INVALID_PATH = "INVALID_PATH"
DUPLICATE_METADATA = "DUPLICATE_METADATA"
UNREADABLE_FILE = "UNREADABLE_FILE"

ATTACHMENT_INTEGRITY_STATUSES = frozenset(
    {
        OK,
        MISSING_FILE,
        ORPHAN_FILE,
        INVALID_PATH,
        DUPLICATE_METADATA,
        UNREADABLE_FILE,
    }
)

ATTACHMENT_INTEGRITY_ERROR_STATUSES = frozenset(
    {
        MISSING_FILE,
        INVALID_PATH,
        DUPLICATE_METADATA,
        UNREADABLE_FILE,
    }
)

ATTACHMENT_INTEGRITY_WARNING_STATUSES = frozenset({ORPHAN_FILE})
